name: Desktop OS Builds

on:
  workflow_call:
  workflow_dispatch:

env:
  CMAKE_VERSION: 3.18.3
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Build", artifact: "Windows.tar.xz",
            os: windows-latest,
            build_type: "Release", cc: "gcc-9", cxx: "g++-9",
            cmake_platform: "",
            # On msvc, the -j flag does not help build times and causes intermittent
            # file permission errors.
            cmake_number_of_jobs: ""
          }
        - {
            name: "Ubuntu Build", artifact: "Linux.tar.xz",
            os: ubuntu-18.04,
            build_type: "Release", cc: "gcc-9", cxx: "g++-9",
            cmake_platform: "",
            glibc_version: "2_27",
            cmake_number_of_jobs: "-j 2" 
          }

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install nasm
      if: ${{ runner.os == 'Windows' }}
      run: choco install nasm
    
    - name: Update Submodules
      run: git submodule update --init --recursive --depth=1

    - name: Add msbuild to PATH
      if: ${{ (runner.os == 'Windows') }}
      uses: microsoft/setup-msbuild@v1.1

    - name: Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.config.os }}
        variant: sccache

    - name: cache stats
      run: sccache --show-stats

    - name: Configure
      shell: devCmd
      run: cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=$ENV{BUILD_TYPE} -D CMAKE_C_COMPILER_LAUNCHER=sccache  -D CMAKE_CXX_COMPILER_LAUNCHER=sccache ${{ matrix.config.cmake_platform }}

    - name: cache stats
      run: sccache --show-stats

    - name: Build
      shell: devCmd
      run: cmake --build build --config $ENV{BUILD_TYPE} ${{ matrix.config.cmake_number_of_jobs }}

    - name: cache stats
      run: sccache --show-stats

    # The generated source in git must match the output of workflow builds.
    # If this step fails, something is changing during build. Either:
    # 1. Fix non-deterministic codegen, OR
    # 2. Build locally to ensure generated files are up-to-date.
    - name: Check for files dirtied by codegen
      run: git diff --exit-code

    - name: Run Tests
      shell: cmake -P {0}
      run: |
        include(ProcessorCount)
        ProcessorCount(N)

        execute_process(
          COMMAND ctest -j ${N} -C $ENV{BUILD_TYPE} -E System --output-on-failure
          WORKING_DIRECTORY build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
            message(FATAL_ERROR "Running tests failed!")
        endif()

    - name: Tar Linux Server Binaries
      if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/releases')) && (runner.os == 'Linux') }}
      run: >-
        tar -cvzf ni-grpc-device-server-linux-glibc${{ matrix.config.glibc_version }}-x64.tar.gz
        -C ${GITHUB_WORKSPACE}/build
        ni_grpc_device_server
        server_config.json
        -C ${GITHUB_WORKSPACE}
        LICENSE
        ThirdPartyNotices.txt

    - name: Upload Linux Server Binaries Artifact
      uses: actions/upload-artifact@v2
      if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/releases')) && (runner.os == 'Linux') }}
      with:
        name: ni-grpc-device-server-linux-glibc${{ matrix.config.glibc_version }}-x64
        path: ni-grpc-device-server-linux-glibc${{ matrix.config.glibc_version }}-x64.tar.gz
        retention-days: 5

    - name: Tar Linux Test Binaries
      if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/releases')) && (runner.os == 'Linux') }}
      run: >-
        tar -cvzf ni-grpc-device-tests-linux-glibc${{ matrix.config.glibc_version }}-x64.tar.gz
        -C ${GITHUB_WORKSPACE}/build
        certs/
        IntegrationTestsRunner
        libTestApi.so
        SystemTestsRunner
        test_mutual_tls_config.json
        UnitTestsRunner
        -C ${GITHUB_WORKSPACE}
        LICENSE
        ThirdPartyNotices.txt

    - name: Upload Linux Test Binaries Artifact
      uses: actions/upload-artifact@v2
      if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/releases')) && (runner.os == 'Linux') }}
      with:
        name: ni-grpc-device-tests-linux-glibc${{ matrix.config.glibc_version }}-x64
        path: ni-grpc-device-tests-linux-glibc${{ matrix.config.glibc_version }}-x64.tar.gz
        retention-days: 5

    - name: Upload Windows Server Information Artifact
      uses: actions/upload-artifact@v2
      if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/releases')) && (runner.os == 'Windows') }}
      with:
        name: ni-grpc-device-server-windows-x64
        path: |
          LICENSE
          ThirdPartyNotices.txt
        retention-days: 5

    - name: Upload Windows Server Binaries Artifact
      uses: actions/upload-artifact@v2
      if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/releases')) && (runner.os == 'Windows') }}
      with:
        name: ni-grpc-device-server-windows-x64
        path: |
          build/Release/ni_grpc_device_server.exe
          build/Release/server_config.json
        retention-days: 5

    - name: Upload Windows Test Binaries Artifact
      uses: actions/upload-artifact@v2
      if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/releases')) && (runner.os == 'Windows') }}
      with:
        name: ni-grpc-device-tests-windows-x64
        path: |
          build/Release/certs/
          build/Release/IntegrationTestsRunner.exe
          build/Release/TestApi.dll
          build/Release/SystemTestsRunner.exe
          build/Release/test_mutual_tls_config.json
          build/Release/UnitTestsRunner.exe
          LICENSE
          ThirdPartyNotices.txt
        retention-days: 5
